### ISSUE TITLE
Switch to hugo

### ISSUE THREAD

**Issue by benmarwick** [sslarch/sslarch.github.io#9] opened 2018-03-29 17:19 UTC
Looks like you are using jekyll here? Have you taken a look at blogdown? It uses Hugo and is a much smoother experience rendering pages and so on. You never need to leave the R console. Documentation is excellent: https://bookdown.org/yihui/blogdown/ It might make it easier to have community contributions if it is as simple as possible to edit pages, etc. Just a thought!

**Comment by nevrome** [comment] 2018-03-29 17:31
We went the [RStudio way](https://rmarkdown.rstudio.com/rmarkdown_websites.html) here. Jekyll should not do anything. But as I look at it I see that there's no .nojekyll file yet. Should add this, I guess. Maybe that's what caused the trouble today in the afternoon, @MartinHinz?

**Comment by benmarwick** [comment] 2018-03-29 17:56
I see, thanks. I wasn't familiar with that method, but now I see that it looks very easy and similar to blogdown. There is no Jekyll involved, my mistake.

**Comment by joeroe** [comment] 2020-11-06 12:56
As the website gets more complicated I also think we might consider blogdown. The workflow is basically the same, but will let us organise things into categories and e.g. easily render the meeting minutes as proper pages. There are some instructions for using blogdown with GitHub Pages here: https://bookdown.org/yihui/blogdown/github-pages.html.

**Comment by nevrome** [comment] 2020-11-08 15:16
Well - I guess we could as well change to blogdown, but what exactly would we win over the current setup?

I think there is rather an argument to be made to ditch R altogether and switch to a static system like docsify. That would make editing the page more easy. Could be done on github in the browser then.

**Comment by joeroe** [comment] 2021-01-11 07:34
What I like about static site generators (and we yeah could ditch the Rmd step and go with straight hugo or jekyll) is the tools for organising content. We could for example turn the current sections for sessions and meeting minutes into hugo archetypes, keeping the markdown content the same, and just as easy to edit, but getting a consistent layout, index pages, taxonomies, and a dated feed "for free".

I haven't used docsify, but it seems the ease of editing is about the same with any system based on markdown? It's R that's adding the extra step, and we probably don't really need it.

If you don't mind, maybe it's easier if I start a branch and prototype something so you can see what I mean.

**Comment by nevrome** [comment] 2021-01-11 07:39
Go ahead :+1: - I have no strong opinions how the content should be rendered.

**Comment by MartinHinz** [comment] 2021-01-11 09:37
Thank you for the proposal and the offer! I personally have only experience with Jekyll so far, but maybe Hugo is the choice? The archetype-thing sounds very interesting!

Btw, there were some complains about the color scheme of the current website, something to discuss at the next meeting!?

**Comment by zackbatist** [comment] 2021-01-11 14:19
Yeah, there were some concerns about accessibility for the website. I'll create an issue about that.

**Comment by joeroe** [comment] 2021-01-12 07:18
Okay I have a rough prototype using hugo (without R/blogdown) at <http://joeroe.io/sslarch.github.io/>. It's automatically built from <https://github.com/joeroe/sslarch.github.io> on push using a GitHub Action.

The main advantage I see is the automatic organisation into sections with a menu and indexes, which can be easily extended by just adding new md files and directories. We can also customise the way specific types of content display in lists and as a single view, see e.g. the members list.

For the sake of time I didn't replicate the style we're currently using, just picked an off-the-shelf hugo theme that's close to it. We can easily reproduce the old one or [go with something else](https://themes.gohugo.io/) if that's what's preferred. Also note that the members list is no longer a tsv. It would be possible to get that functionality back by writing an R script that generates .md pages from a table, like Zack does with [zackbatist/open-archaeo](/zackbatist/open-archaeo), although I don't think asking new members to "sign up" by creating a file for themselves in `content/members/` would be that bad either?

**Comment by zackbatist** [comment] 2021-01-12 13:20
Looks great to me! My only suggestion would be to [add breadcrumbs](http://hugocodex.org/add-ons/breadcrumbs/) to help determine the logical organization of the site and navigate accordingly.

**Comment by joeroe** [comment] 2021-01-13 10:43
@zackbatist Good idea. I've added them.

**Comment by nevrome** [comment] 2021-01-18 13:41
I love it. The layout is also fine for me. Some small suggestions, @joeroe (not necessarily to be fixed by you):

- [ ] The `CAA/SSLA $` icon in the top left still leads to your own homepage, @joeroe (maybe this is fixed automatically after merging?)
- [ ] The page should prominently feature our logo (the logo might also guide the selection of the colour theme)
- [ ] The Steering Committee members in `members` should not be ordered alphabetically, but according to their role: Convener - Vice Convener - Secretary
- [ ] The `sessions` tab should get a better menu layout

**Comment by joeroe** [comment] 2021-01-19 18:43
Those should all be straightforward (and yes the first is just me being lazy with the config files and won't be there after merging). I can do them or if others want to try out the new system PRs are welcome!

**Comment by nevrome** [comment] 2021-01-19 21:33
Please add (or replace the available one) a quickstart guide to the README to explain how this hugo thing works in brief words. You should also explain the git submodule and how to get it.

**Comment by nevrome** [comment] 2021-01-19 21:35
The idea should be to give people an immediate ability to develop without opening the hugo or git man pages.

**Comment by joeroe** [comment] 2021-02-03 18:11
Since we decided to go ahead with this at the last meeting, I'd like to tidy up the code and improve the presentation before we go live (including the items above, #37 and #38). Nothing major, but it will take me a few days before it's ready for a PR.

**Comment by joeroe** [comment] 2021-03-05 12:02
An update on the new site at http://joeroe.io/sslarch.github.io/ (source https://github.com/joeroe/sslarch.github.io):

* Changed the theme to a [custom one](https://github.com/joeroe/risotto) that is more flexible
* Added the logo and changed the colour scheme to match it
* Improved the typography, inspired by the current website
* Improved the accessibility (#37)
* Documented how to build and change the site in README.md

As long as the group still approves, I think this is very close to being ready. There are just a few issues I haven't had time to fix yet:

- [ ] Re-add breadcrumbs as suggested by @zackbatist 
- [ ] Implement and document the new member process in #38 
- [ ] Improve the layout of the sessions menu and pages
- [ ] Add dates and authors to pages where applicable
- [ ] Improve the minutes layout, e.g. to add links to the previous/next minutes
- [ ] Improve the rendering of ASCII art, e.g. at http://joeroe.io/sslarch.github.io/about/
- [ ] Render the table at the bottom of http://joeroe.io/sslarch.github.io/documents/caa_proposal/

**Comment by MartinHinz** [comment] 2021-03-05 13:05
Thank you so much! From my perspective, these are all things that we can also implement once this version is merged. So, I would suggest to PR right away?

**Comment by nevrome** [comment] 2021-03-05 14:29
Ja - let's merge and we fix it together in post-production :+1:

**Closed** 2021-04-01 06:32 UTC
